@startuml
skinparam svgDimensionStyle false
title [[https://profiles.ihe.net/ITI/MHDS/index.html Mobile Health Document Sharing (MHDS)]]\n a simple clinical app scenario
participant "Clinical App\n and user" as App
participant "Health Information Exchange\nMHDS Registry\n other FHIR Services" as HIE [[https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html HIE-Whitepaper]]
autonumber
Note right of App: Configured \n - Certificate Authority\n - App identity\n - time sync source\n - HIE endpoint\n - Audit Repository endpoint

App -> App: Patient presents
activate App

group App/User Authorization with OAuth (IUA)
App -> HIE: query OAuth metadata at endpoint
App -> HIE: request authorization 
App <-- HIE: Token granted
Note left of App: use this token in all the following 
activate App #SeaGreen
activate HIE #SeaGreen
end group

group Communication Security (ATNA)
App -> HIE: ATNA Secure Communication **opened**
end group

group Security Logging (ATNA)
App -> HIE: ATNA record AuditEvent details
Note left of App: repeat as auditable events happen
end group

Note left of App: Find patient identity in HIE
group Patient Identity Lookup (PDQm/PIXm)
App -> HIE: Search for Patient by name or id or etc
App <-- HIE: Some set of best can be found results
end group

App -> App: Pick best of best Patient identity

group Patient Identity Management (PMIR) 
App -> App: Patient indicate last name change
App -> HIE: Update golden Patient with new last name
end group

alt Find existing Medical Summary
    group Document Discovery (MHD/MHDS)
    App -> HIE: MHD ITI-67: are there any Medical Summary?
    App <-- HIE: results

    App -> App: pick latest or OnDemand 

    App -> HIE: MHD ITI-68 Get Medical Summary
    App <-- HIE: Here is the latest Medical Summary
    end group

    Note left of App: Medical Summary [[https://www.hl7.org/ccdasearch/ C-CDA]] or [[https://hl7.org/fhir/uv/ips/ IPS]]

else FHIR Resources
    group Query for Existing Data (QEDm)
    participant "Data Element Extractor" as Extractor
    App -> HIE: [[https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_Suppl_QEDm.pdf QEDm]] Query for various FHIR Resources
    HIE -> HIE: Request for QEDm type resources triggers Extractor given cache is empty
    group Data Element Extractor
    HIE-> Extractor : [[https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_mXDE.pdf mXDE]] Extract Elements from available Documents
    activate Extractor #Salmon
    Extractor -> HIE: MHD ITI-67: are there any Medical Summary?
    Extractor <-- HIE: results
    loop for all results
    Extractor -> HIE: MHD ITI-68 Get document
    Extractor <-- HIE: results
    Extractor -> Extractor: Decompose document content to FHIR Resources
    Extractor -> Extractor: De-Duplicate Resources to just new FHIR Resources
    Extractor -> HIE: Persist new FHIR Resources
    Extractor -> HIE: Persist Provenance for document to each Resource found (previous and new)
    end loop
    HIE <-- Extractor : done
    deactivate Extractor
    end group

    App <-- HIE: Query results
    App -> HIE: QEDm query
    App <-- HIE: Query results
    end group
end

    App -> App: utalize Medical information to treat patient

group Codes, ValueSet and Concept Maps (SVCM) 
App -> HIE: Lookup codes, valuesets, or concept mapping
App <-- HIE: use this code
end group

group Provider Directory (mCSD) 
App -> HIE: search for oncologists for referral
App <--  HIE: List of oncologists 
end group 

Note left of App: Author a Referral Request [[https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_Suppl_360X.pdf 360X]]

group Publish Document (MHD/MHDS)
App -> HIE: MHD ITI-65 Publish Referral Request 
HIE->HIE: MHDS Document Registry persists
App <-- HIE: success
end group

Note left of App: Provide Patient with oncologists 

Note Left of App: Done with Secure Communication
App <-- HIE: ATNA Secure Communication **closed**
deactivate App
deactivate HIE


deactivate App


@enduml
